name: uae_api_client

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  very_good_analysis: ^3.1.0

dev_dependencies:
  lints: ^2.0.1
