name: event_repository
description: repository for fetching events from RESTful API

version: 0.0.1

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  uae_api_client:
    path: ../server_api_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:

